"""
This type stub file was generated by pyright.
"""

from .album import *
from .artist import *
from .client import *
from .image import *
from .paginator import *
from .tag import *
from .track import *
from .user import *
from .wiki import *
