"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional, Self

import aiohttp

from .album import Album
from .artist import Artist
from .track import Track
from .user import User

__all__ = ("Client",)

class Client:
    def __init__(
        self, api_key: str, *, session: Optional[aiohttp.ClientSession] = ...
    ) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, *args: Any) -> None: ...
    async def close(self) -> None: ...
    async def get_album_info(
        self,
        artist: Optional[str] = ...,
        album: Optional[str] = ...,
        *,
        mbid: Optional[str] = ...,
        autocorrect: Optional[bool] = ...,
        username: Optional[str] = ...,
        lang: Optional[str] = ...
    ) -> Album: ...
    async def get_artist_info(
        self,
        artist: Optional[str] = ...,
        *,
        mbid: Optional[str] = ...,
        autocorrect: Optional[bool] = ...,
        username: Optional[str] = ...,
        lang: Optional[str] = ...
    ) -> Artist: ...
    async def get_track_info(
        self,
        artist: Optional[str] = ...,
        track: Optional[str] = ...,
        *,
        mbid: Optional[str] = ...,
        autocorrect: Optional[bool] = ...,
        username: Optional[str] = ...
    ) -> Track: ...
    async def get_user_info(self, user: str) -> User: ...
    async def search_albums(
        self, album: str, *, limit: Optional[int] = ..., page: Optional[int] = ...
    ) -> List[Album]: ...
    async def search_artists(
        self, artist: str, *, limit: Optional[int] = ..., page: Optional[int] = ...
    ) -> List[Artist]: ...
