"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict

class LastFMException(Exception): ...

class HTTPException(LastFMException):
    def __init__(self, response: Dict[str, Any]) -> None: ...
