"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict

__all__ = ("Wiki",)

class Wiki:
    __slots__ = ...
    def __init__(self, data: Dict[str, Any]) -> None: ...
    def __repr__(self) -> str: ...
