owner_id=1

[tokens]
bot=""
testing_bot=""

[keys]
fishie_api=""
lastfm=""
lastfm_secret=""
google=""
google_id=""
spotify_id=""
spotify_secret=""

[databases]
postgre_dsn=""
testing_postgre_dsn=""

redis_dsn=""
testing_redis_dsn=""

[webhooks]
avatars=[]

images=[]


icons=[]
