[tokens]
bot = ""
testing_bot = ""

[keys]
fishie_api = ""
lastfm = ""
lastfm_secret = ""
google = [
    "",
    "",
    "",
]
google_id = ""
spotify_id = ""
spotify_secret = ""
dagpi = ""

[databases]
psql = ""
psql_testing = ""

redis = ""
redis_testing = ""

[twitter]
username = ""
password = ""

[ids]
owner_id = 1
bot_id = 1
poketwo_id = 1
mudae_id = 1
join_logs_id = 1

[webhooks]
images = []
error_logs = ""